### ISSUE TITLE
Async await usage

### ISSUE THREAD

**Issue by nihiluis** [carllerche/pool#11]
How does this work with async await?

I assume that, if the pool is depleted, the async event loop would be blocked. Is that correct?

**Comment by kw217** [comment]
`checkout` returns `None` in this case, in which case you should push a waker somewhere and return `Poll::Pending` from your `poll_ready`. Then when you put something into the pool, you should wake the waker(s).

It would be nice if this was provided as part of this library, but it's not too hard to code.
