### ISSUE TITLE
Pool.inner_mut() and other mut methods are UB

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/pool#2]
According to this doc page http://doc.rust-lang.org/1.0.0-beta/std/cell/struct.UnsafeCell.html, transmuting &T to &mut T is undefined behavior. I believe rustc tells llvm they are readonly unless the unsafe lang item is used, which is UnsafeCell.

**Comment by carllerche** [comment]
Hmmm.... so what about transmuting `*mut T` -> `&mut T`, is that permitted? Should `PoolInner` be wrapped in an `UnsafeCell`?

**Comment by seanmonstar** [comment]
I do not know if that's safe. However, you can easily do `let a = &mut *ptr;` to get `&mut T` from a `*mut T`.

**Comment by seanmonstar** [comment]
Finally filed that PR for a lint as well: https://github.com/rust-lang/rust/pull/24392
